# The secrets file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=R00t
- name: mysql-user-pass
  literals:
  - username=callicoder
  - password=c@ll1c0d3r 
- name: mysql-db-url
  literals:
  - database=polls
  - url=jdbc:mysql://mysql:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
resources:
  - api.yaml
  - frontend.yaml  
  - ingress.yaml  
  - mysql.yaml
